In [1]:
import numpy as np
import cv2
import os
import datetime


#Face detection is done
def faceDetection(test_img):             
    gray_img=cv2.cvtColor(test_img,cv2.COLOR_BGR2GRAY)
    face_haar=cv2.CascadeClassifier(r'D:\Python video\18 Python for Image and Video Processing with OpenCV\170 Files\haarcascade_frontalface_default.xml') #Give path to haar classifier as i have given
    faces=face_haar.detectMultiScale(gray_img,scaleFactor=1.2,minNeighbors=3)
    return faces,gray_img

#Labels for training data has been created

def labels_for_training_data(directory):
    faces=[]
    faceID=[]
    

    for path,subdirnames,filenames in os.walk(directory):
        for filename in filenames:
            if filename.startswith("."):
                print("skipping system file")
                continue
            id=os.path.basename(path)
            img_path=os.path.join(path,filename)
            print ("img_path",img_path)
            print("id: ",id)
            test_img=cv2.imread(img_path)
            if test_img is None:
                print ("Not Loaded Properly")
                continue

            faces_rect,gray_img=faceDetection(test_img)
            if len(faces_rect)!=1:
                continue
            (x,y,w,h)=faces_rect[0]
            roi_gray=gray_img[y:y+w,x:x+h]
            faces.append(roi_gray)
            faceID.append(int(id))
    return faces,faceID


#Here training Classifier is called
def train_classifier(faces,faceID):                              
    face_recognizer=cv2.face.LBPHFaceRecognizer_create()
    face_recognizer.train(faces,np.array(faceID))
    return face_recognizer


#Drawing a Rectangle on the Face Function
def draw_rect(test_img,face):                                      
    (x,y,w,h)=face
    cv2.rectangle(test_img,(x,y),(x+w,y+h),(0,255,0),thickness=3)

#Putting text on images
def put_text(test_img,text,x,y):                                    
    cv2.putText(test_img,text,(x,y),cv2.FONT_HERSHEY_DUPLEX,3,(255,0,0),6)
    



In [2]:
import numpy as np
import cv2
import os
import datetime

# import faceRecognition as fr
# print (fr)



face_recognizer=cv2.face.LBPHFaceRecognizer_create()
face_recognizer.read(r'D:\Python video\18 Python for Image and Video Processing with OpenCV\170 Files\trainingData3.yml')    #Give path of where trainingData.yml is saved

cap1=cv2.VideoCapture(1)   #If you want to recognise face from a video then replace 0 with video path

def timework(name):
    with open('t5.csv','+r') as f:
        myDatalist=f.readlines()
        nameList=[]
        for line in myDatalist:
            entry=line.split(',')
            nameList.append(entry[0])
        if name not in nameList:
            now_=datetime.datetime.now()
            dtString=now_.strftime('%H:%M:%S')
            f.writelines(f'\n{name}{dtString}')

name={0:"logeshwaram",1:"Abishek"}    #Change names accordingly.  If you want to recognize only one person then write:- name={0:"name"} thats all. Dont write for id number 1.
while True:
    ret1,test_img=cap1.read()
    faces_detected,gray_img=faceDetection(test_img)
    print("face Detected: ",faces_detected)
    for (x,y,w,h) in faces_detected:
        cv2.rectangle(test_img,(x,y),(x+w,y+h),(0,255,0),thickness=5)

    
    
    for face in faces_detected:
        (x,y,w,h)=face
        roi_gray=gray_img[y:y+h,x:x+h]
        label,confidence=face_recognizer.predict(roi_gray)
        print ("Confidence :",confidence)
        print("label :",label)
        draw_rect(test_img,face)
        timework(name[label])
        predicted_name=name[label]
        if confidence>=75:
            predicted_name = 'Unknown'
        else:
            predicted_name=name[label]
        put_text(test_img,predicted_name,x,y)
    
    '''for face in faces_detected:
        (x,y,w,h)=face
        roi_gray=gray_img[y:y+h,x:x+h]
        label,confidence=face_recognizer.predict(roi_gray)
        print ("Confidence :",confidence)
        print("label :",label)
        draw_rect(test_img,face)
        timework(name[label])
        if confidence <=20:
            predicted_name = 'Unknown'
        else:
            predicted_name=name[label]
        put_text(test_img,predicted_name,x,y)

    resized_img=cv2.resize(test_img,(1000,700))'''

    resized_img=cv2.resize(test_img,(1000,700))

    cv2.imshow("face detection ", resized_img)
    if cv2.waitKey(10)==ord('q'):
        break


face Detected:  [[404 207  47  47]
 [394 398  51  51]]
Confidence : 164.07251181092738
label : 0
Confidence : 154.43307964496805
label : 0
face Detected:  [[403 206  50  50]
 [390 399  52  52]]
Confidence : 151.67369632823505
label : 0
Confidence : 154.43416022170058
label : 0
face Detected:  [[230 220 177 177]]
Confidence : 70.31809999254837
label : 1
face Detected:  [[240 226 183 183]]
Confidence : 70.1438011457985
label : 1
face Detected:  [[229 216 203 203]]
Confidence : 69.8743519824755
label : 1
face Detected:  [[228 219 198 198]]
Confidence : 69.54465503175832
label : 1
face Detected:  [[228 218 198 198]]
Confidence : 69.43269895758812
label : 1
face Detected:  [[224 218 204 204]]
Confidence : 70.72899401164555
label : 1
face Detected:  [[226 221 200 200]]
Confidence : 72.1877292458951
label : 1
face Detected:  [[226 220 203 203]]
Confidence : 71.69973755019748
label : 1
face Detected:  ()
face Detected:  [[400 404  60  60]
 [227 228 195 195]]
Confidence : 141.63743882308415
lab

: 